### ISSUE TITLE
Infografia  Actividad 1

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-1-infografia-HECTOR-KDM02#1]
[22620040-infografia.pdf](https://github.com/user-attachments/files/16754665/22620040-infografia.pdf)

Infografia

**Comment by Bryan080204** [comment]
20 (Esta bien estructurada) informacion ,colores etc.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
